language: java
sudo: false
install: mvn -Ptravis -DskipTests=true -Dmaven.javadoc.skip=true -e -B -V install
script: mvn ${JACOCO} -Ptravis -Dmaven.javadoc.skip=true -e -q -B verify
matrix:
 include:
   # Covers Java 7, Open JDK, and code coverage
   - jdk: openjdk7
     env: JACOCO=-Pjacoco
   # Covers Java 8, Oracle JDK
   - jdk: oraclejdk8
cache:
  directories:
    - $HOME/.m2
git:
  depth: 5
after_success: if [ -n "$JACOCO" ]; then bash <(curl -s https://codecov.io/bash); fi
env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "VD4OWXLN2PS6Rgfdk7+h9Oau32sNOdkvjDRzbVJwFZyzKBZh61p3KK/v5/N01MTxqxgQybd2Y6gXviUd1cDvB07AdDpI7gU9ZkWuPK6YEyo1k2Sv+Lhh+wYW4UzIrpE6gJoVCm4u9ptYWqAzbrWzL1kuCNaoBU3EsjH0C3JaNTU="
addons:
 coverity_scan:
   project:
     name: "cloudera/oryx"
     description: "Build submitted via Travis CI"
   notification_email: srowen@gmail.com
   build_command_prepend: "mvn clean"
   build_command: "mvn -DskipTests=true compile test-compile"
   branch_pattern: coverity_scan